fish895623/joe_shop

build.gradle, src/main/java/com/bit/joe/shoppingmall/entity/Cart.java, src/main/java/com/bit/joe/shoppingmall/entity/Category.java, src/main/java/com/bit/joe/shoppingmall/entity/Order.java, src/main/java/com/bit/joe/shoppingmall/entity/OrderItem.java, src/main/java/com/bit/joe/shoppingmall/entity/Product.java, src/main/java/com/bit/joe/shoppingmall/entity/User.java, src/main/java/com/bit/joe/shoppingmall/enums/UserGender.java, src/main/java/com/bit/joe/shoppingmall/enums/UserRole.java, src/main/java/com/bit/joe/shoppingmall/repository/CategoryRepository.java, src/main/java/com/bit/joe/shoppingmall/repository/OrderItemRepository.java, src/main/java/com/bit/joe/shoppingmall/repository/OrderRepository.java, src/main/java/com/bit/joe/shoppingmall/repository/ProductRepository.java, src/main/java/com/bit/joe/shoppingmall/repository/UserRepository.java, src/main/resources/application.properties
1. created Entity package done. using JPA -> no need to use SQL queries to build DB tables.
2. created Enum package done and it replaces role & gender entity classes
3. created Repo package done.
- 늦은 밤 죄송합니다. 낮잠을 너무 많이 자서 밤늦게 쌩쌩해졌네요!! 취침시간에는 방해금지 모드가 되어있겠지 한 번 pull request를 해봅니다...
- shoppingmall 이라는 db 생성 해주시고, app을 run만 하면 자동으로 tabels 만들어집니다. 나중에 같이 보고 수정하고 싶은거 회의 하면 됩니다.
- 각자 mysql root name과 password가 다를 것이라 생각됩니다. 저도 그렇고. new usename을 bit, password를 1234로 통일 해주시고 bit에게 shoppingmall 권한은 GRANT ALL PRIVILEGES으로 주시기를 부탁드립니다.
=> create db tables and repo

src/main/java/com/bit/joe/shoppingmall/enums/UserGender.java
=> Add Gender

README.md, build.gradle, src/main/java/com/bit/joe/shoppingmall/contoller/CategoryController.java, src/main/java/com/bit/joe/shoppingmall/contoller/ProductController.java, src/main/java/com/bit/joe/shoppingmall/controller/ThymeleafExController.java, src/main/java/com/bit/joe/shoppingmall/dto/CategoryDto.java, src/main/java/com/bit/joe/shoppingmall/dto/ProductDto.java, src/main/java/com/bit/joe/shoppingmall/entity/Product.java, src/main/java/com/bit/joe/shoppingmall/service/CategoryService.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CategoryServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/ProductServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/ProductService.java, src/main/resources/templates/thymeleaf/thymeleaf.html, src/main/resources/templates/thymeleaf/thymeleaf2.html
- Make controller, views example..?
=> Controller, Views for test

src/main/java/com/bit/joe/shoppingmall/controller/CategoryController.java, src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java
오타 수정 (contoller -> controller)
=> Typo Correction

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/dto/UserDto.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/UserService.java
- UserController.java
- UserDto.java
- UserService.java (interface)
- UserServiceImpl.java (구현객체)
=> Setup Package of control, service for User

build.gradle, src/main/java/com/bit/joe/shoppingmall/controller/CategoryController.java, src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/dto/UserDto.java, src/main/java/com/bit/joe/shoppingmall/exception/InvalidCredentialsException.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/UserService.java
- CatatoryController done
- ProductController done
- SecurityConfig to be filled
- add one more Exception file
=> created controllers done

src/main/java/com/bit/joe/shoppingmall/mapper/CategoryMapper.java, src/main/java/com/bit/joe/shoppingmall/mapper/ProductMapper.java, src/main/java/com/bit/joe/shoppingmall/mapper/UserMapper.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CategoryServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/ProductServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/resources/application.properties
1. mappers for category/product added
2. add @Component annotation to UserMapper.java
3. add BCryptPasswordEncoder to createUser() method in UserServiceImpl.java
=> add mappers for product/category

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/UserService.java
- add mapping methods in UserController
=> Feat: Implement user management features with security configuration

docs/2025_02_25.md
=> Documentation

src/main/java/com/bit/joe/shoppingmall/entity/Cart.java, src/main/java/com/bit/joe/shoppingmall/entity/Order.java, src/main/java/com/bit/joe/shoppingmall/entity/OrderItem.java, src/main/java/com/bit/joe/shoppingmall/enums/OrderStatus.java
- 데이터베이스 엔티티 변경
이 글을 지우고 관계 없는 아래 항목중 관계 없는 내용은 지워주세요
=> refactor: Simplify Cart and Order models, introduce OrderStatus enum

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/repository/UserRepository.java, src/main/java/com/bit/joe/shoppingmall/security/CustomUserDetails.java, src/main/java/com/bit/joe/shoppingmall/security/CustomUserDetailsService.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java
- Add custom user details and security configuration for user authentication
=> feat: Add custom user details and security configuration for user authentication

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/enums/OrderStatus.java, src/main/java/com/bit/joe/shoppingmall/security/CustomUserDetails.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/UserService.java
=> Refactor user login api

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/security/CustomAuthenticationProvider.java, src/main/java/com/bit/joe/shoppingmall/security/CustomUserDetails.java, src/main/java/com/bit/joe/shoppingmall/security/CustomUserDetailsService.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java
- [refactor: Update user identification method to use email instead of name](https://github.com/fish895623/joe_shop/commit/e51a52bcc7f9418aac88d96dd2699145b1269b8c)
사용자 권한 확인 시 이메일이 아닌 사용자의 이름으로 확인하고 있었음
- 주석 추가 및 불필요한 파라미터 삭제
=> Refactor some codes in "User" part, "Security" part

src/main/java/com/bit/joe/shoppingmall/entity/User.java
- User 엔티티 내 email, unique로 변경
- 회원 가입 시 email 중복 불가
- #33 
- DB
- 테이블 삭제 후 재실행 해야 적용 됩니다. 
귀찮으신 분은 스크립트 실행 부탁드립니다.
`ALTER TABLE users
ADD CONSTRAINT unique_email UNIQUE (email);`
=> feat: make email unique in user entity

build.gradle, src/main/java/com/bit/joe/shoppingmall/dto/OrderDto.java, src/main/java/com/bit/joe/shoppingmall/dto/OrderItemDto.java, src/main/java/com/bit/joe/shoppingmall/entity/Order.java, src/main/java/com/bit/joe/shoppingmall/entity/OrderItem.java, src/main/java/com/bit/joe/shoppingmall/mapper/OrderItemMapper.java, src/main/java/com/bit/joe/shoppingmall/mapper/OrderMapper.java
- Setting for Order, Order-Item api
- 세팅
=> Setting for Order, Order-Item api

src/test/java/com/bit/joe/shoppingmall/controller/ProductControllerTests.java
=> fix: Update HTTP status code in test methods

src/main/java/com/bit/joe/shoppingmall/controller/CartController.java, src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java, src/main/java/com/bit/joe/shoppingmall/controller/OrderController.java
- Needs RestController for swagger
- 어노테이션이 없어져서 swagger-UI 에서 작동하지 않음
이 글을 지우고 관계 없는 아래 항목중 관계 없는 내용은 지워주세요
=> Fix missing annotations

src/main/java/com/bit/joe/shoppingmall/controller/OrderController.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java
- [feat: api for Order Return process](https://github.com/fish895623/joe_shop/commit/4d5e1dd6c949a37851ae7d462d537d579a43592e)
- 기능 추가
- POSTMAN
=> feat: api for Order Return process

src/main/java/com/bit/joe/shoppingmall/controller/OrderController.java, src/main/java/com/bit/joe/shoppingmall/dto/request/OrderRequest.java, src/main/java/com/bit/joe/shoppingmall/enums/RequestType.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java
- make handling method (handle all of the request of order)
- CAUTION: api path changed to '/api/order/request'
- now read requestType in OrderRequest to handling several requests.
- #58 
- change api path
- add request type
=> refactor: add order request handling function

build.gradle, src/main/java/com/bit/joe/shoppingmall/entity/Category.java, src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java, src/test/java/com/bit/joe/shoppingmall/service/CategoryServiceTests.java
=> test: CategoryService TestCase

src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java
- add logic to function appendProductToCart in CartService.java
- create new cart when cart is not exist
=> refactor: add logic add product to cart when cart is not exist

src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/ProductControllerTests.java
=> test: Remove `@Order` annotations from tests

src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/test/java/com/bit/joe/shoppingmall/controller/UserControllerTests.java
- (feat: withdraw user test)[feat: withdraw user test](https://github.com/fish895623/joe_shop/commit/b400fa7b96bb40dfaf087f7dca9ada4cb2fd2059)
=> feat: withdraw user test

src/main/java/com/bit/joe/shoppingmall/controller/InventoryController.java, src/main/resources/templates/thymeleaf/admin/insight.html, src/main/resources/templates/thymeleaf/admin/inventory.html, src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java
- inventoryController, inventory.html 생성
=> Psa-view-admin-inventory

src/main/java/com/bit/joe/shoppingmall/controller/CartHtmlController.java, src/main/java/com/bit/joe/shoppingmall/controller/HistoryController.java, src/main/java/com/bit/joe/shoppingmall/controller/ProductdetailController.java, src/main/resources/templates/thymeleaf/product/cart.html, src/main/resources/templates/thymeleaf/product/history.html, src/main/resources/templates/thymeleaf/product/product-detail.html, src/test/java/com/bit/joe/shoppingmall/controller/ProductControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/UserControllerTests.java
- 장바구니, 상세 상품, 히스토리 UI 및 상품 상세 UI 구현, JSON 데이터 불러오기
=> Create product detail page UI and implement JSON data fetching

.gitattributes, .github/workflows/java-version-test.yml, .github/workflows/java.yml, build.gradle, src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java
- [refactor: modify cart-item's get-all api](https://github.com/fish895623/joe_shop/commit/66a38a533359cc27d27fa35b44564687b4a55ca3)
- 기능 변경
- 유저 아이디 기준으로 전부 가져오기
- 전부 가져오기
=> refactor: modify cart-item's get-all api

src/main/resources/templates/thymeleaf/admin/inventory.html
=> modify add nav and json

src/main/resources/templates/thymeleaf/admin/insight.html
- insight modify html table 
이 글을 지우고 관계 없는 아래 항목중 관계 없는 내용은 지워주세요
=> insight modify html table

src/main/resources/templates/thymeleaf/admin/member.html
=> modify nav, add json

src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java
- [feat: enhance OrderService with user context and order date handling](https://github.com/fish895623/joe_shop/pull/98/commits/eb8d6ec34392b422ad02eaf3bd5ea69acc224a50)
- postman authentication
=> feat: enhance OrderService with user context and order date handling

.github/workflows/java.yml, src/main/java/com/bit/joe/shoppingmall/dto/ProductDto.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java, src/test/java/com/bit/joe/shoppingmall/controller/OrderControllerTests.java
=> Create Order TEST

src/main/java/com/bit/joe/shoppingmall/controller/MemberController.java, src/main/resources/templates/thymeleaf/admin/insight.html, src/main/resources/templates/thymeleaf/admin/inventory.html, src/main/resources/templates/thymeleaf/admin/member.html, src/main/resources/templates/thymeleaf/common/footer.html, src/main/resources/templates/thymeleaf/common/navigation.html, src/main/resources/templates/thymeleaf/index.html, src/main/resources/templates/thymeleaf/product/cart.html, src/main/resources/templates/thymeleaf/product/history.html, src/main/resources/templates/thymeleaf/product/product-detail.html, src/main/resources/templates/thymeleaf/thymeleaf.html, src/main/resources/templates/thymeleaf/thymeleaf2.html, src/main/resources/templates/thymeleaf/user/login.html, src/main/resources/templates/thymeleaf/user/mainPage.html, src/main/resources/templates/thymeleaf/user/myPage.html, src/main/resources/templates/thymeleaf/user/signUp.html
- member getmapping, json data 화면 출력
=> member getmapping

src/main/java/com/bit/joe/shoppingmall/controller/OrderController.java, src/main/java/com/bit/joe/shoppingmall/repository/OrderItemRepository.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java, src/test/java/com/bit/joe/shoppingmall/controller/OrderControllerTests.java
- Write order test code
- 기능 추가
- 테스트 실행
=> Order test code (25.03.07)

src/test/java/com/bit/joe/shoppingmall/controller/UserControllerTests.java
- User Controller Test 를 컨테이너에서 H2 로 교체
=> test: refactor UserControllerTests for improved structure and clarity

src/test/java/com/bit/joe/shoppingmall/controller/CartControllerTests.java
=> test: refactor CartControllerTests for improved structure and clarity

src/main/resources/templates/thymeleaf/index.html, src/main/resources/templates/thymeleaf/user/login.html, src/main/resources/templates/thymeleaf/user/mainPage.html, src/main/resources/templates/thymeleaf/user/signUp.html
- mainPage에서 json으로 product.name, product.image, product.price 구현
=> mainPage HTML json

.github/workflows/java.yml, src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java, src/main/java/com/bit/joe/shoppingmall/dto/CartItemDto.java, src/main/java/com/bit/joe/shoppingmall/mapper/CartItemMapper.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartItemServiceImpl.java, src/test/java/com/bit/joe/shoppingmall/controller/CartItemControllerTests.java
- [Enhance cart item update functionality and improve test coverage](https://github.com/fish895623/joe_shop/commit/6995f85c1e63db263360f26c0daa65e739c855e0)
- refactor test code
- just run test
=> CartItem Test Code (25.03.10)

src/main/java/com/bit/joe/shoppingmall/dto/CategoryDto.java, src/main/java/com/bit/joe/shoppingmall/repository/CategoryRepository.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CategoryServiceImpl.java, src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java
- refactor category test code
- sometimes it makes error because of executing test functions in random but test data does not roll backed properly.
- just run TEST
=> Refactor Category Test Code (25.03.10)

src/main/resources/templates/login.html
- Create registration button on login page
=> feat: add registration link to login page

src/main/resources/static/global.js
=> Refactor JWT token handling and improve error logging

src/main/resources/templates/common/navigation.html, src/main/resources/templates/login.html
- Update navigation bar per users
=> fix: change for user and admin and non logged in

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/dto/request/UpdateUserInfoRequest.java, src/main/java/com/bit/joe/shoppingmall/view/UserHtmlController.java, src/main/resources/templates/common/navigation.html, src/main/resources/templates/user/myPage.html
- Display user information and update information
=> bsh-mypage-edit-and-save

src/main/java/com/bit/joe/shoppingmall/view/ProductDetailsController.java, src/main/resources/templates/product/product-detail.html, src/main/resources/templates/user/mainPage.html
=> Product Detail Page

src/main/java/com/bit/joe/shoppingmall/controller/CartController.java, src/main/java/com/bit/joe/shoppingmall/dto/request/CartRequest.java, src/main/java/com/bit/joe/shoppingmall/mapper/CategoryMapper.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/ProductServiceImpl.java, src/test/java/com/bit/joe/shoppingmall/controller/CartControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/CartItemControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/OrderControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/ProductControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/UserControllerTests.java
- 두 번째 테스트 코드 리팩토링
- 버그 수정
- 전체 테스트 실행
=> 2ND / TEST CODE REFACTOR (25.03.10)

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, src/main/java/com/bit/joe/shoppingmall/controller/FileController.java, src/main/java/com/bit/joe/shoppingmall/jwt/JWTFilter.java, src/main/resources/templates/common/head.html, src/main/resources/templates/product/history.html, src/main/resources/templates/user/mainPage.html
- Upload file and save to `uploads`
=> Save Image to local directory

src/main/java/com/bit/joe/shoppingmall/jwt/JWTFilter.java
- When Token Time expired, displays 500 error
=> Jwt Token Expired Error 500

src/main/resources/static/style.css, src/main/resources/templates/common/footer.html, src/main/resources/templates/product/history.html, src/main/resources/templates/product/product-detail.html, src/main/resources/templates/user/mainPage.html, src/main/resources/templates/user/myPage.html
- Footer Overlaped
- Footer not fit to bottom
=> Footer Not Fit to bottom

src/main/java/com/bit/joe/shoppingmall/view/HomeController.java, src/main/resources/static/style.css, src/main/resources/templates/category-list.html, src/main/resources/templates/user/mainPage.html
- **feat: enhance main page layout with category navigation and improved structure**
- **feat: add category list page and update navigation link**
- Link to Category Lists
=> Link to Category Lists

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/security/SecurityConfig.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/UserService.java, src/main/resources/templates/user/mainPage.html, src/test/java/com/bit/joe/shoppingmall/controller/UserControllerTests.java
- Refactor User Controller Test code
- Bug fix
- just run the test
=> Refactor User Controller Test (25.03.11)

src/main/resources/templates/category-list.html, src/main/resources/templates/user/mainPage.html
- Displays Total Category Lists
=> Create Category Lists

src/main/resources/templates/admin/inventory.html, src/main/resources/templates/admin/member.html
- member.html 화면창에 회원정보 불러와서 화면 창에 회원전체 목록이 보이도록
=> member.html 회원전체 목록 화면창에 출력 

src/main/resources/templates/admin/inventory.html
- dropdown 데이터값불러오고 입력 가능하도록, 총 합계 금액 출력
=> dropdown 데이터값 불러오고 입력 가능하도록, 총 합계 금액 출력

src/main/java/com/bit/joe/shoppingmall/controller/CartController.java, src/main/java/com/bit/joe/shoppingmall/controller/OrderController.java, src/main/java/com/bit/joe/shoppingmall/entity/Cart.java, src/main/java/com/bit/joe/shoppingmall/mapper/OrderMapper.java, src/main/java/com/bit/joe/shoppingmall/repository/OrderRepository.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartItemServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/OrderService.java, src/test/java/com/bit/joe/shoppingmall/controller/OrderControllerTests.java
=> Refactor Order Test code (25.03.11)

src/main/java/com/bit/joe/shoppingmall/controller/CartController.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java
- feat: add endpoint to retrieve cart using JWT token for authentication
=> feat: add endpoint to retrieve cart using JWT token for authentication

src/main/resources/templates/admin/member.html
=> modify member URL

src/main/resources/templates/admin/member.html
=> Navigation bar

src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java, src/main/resources/templates/product/product-detail.html, src/test/java/com/bit/joe/shoppingmall/controller/CartControllerTests.java
- Fetch "/api/cart/get" API at the product-detail view
- go to product-detail page, set quantity, click add to cart button
- you can check cart data (found by token)
=> Fetch "/api/cart/get" API at the product-detail view (25.03.11)

src/main/resources/templates/common/navigation.html
- Navigation bar disable horizontal view
=> Navigation bar horizontal view

src/main/resources/templates/admin/inventory.html
- Remove Unnecessary content.
- Replace and add content about data
=> Inventory Table View

src/main/resources/static/global.js, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/product-detail.html
- Please delete this text and add your feature description here
- #149
- Go Product-detail, Click add to cart button, Check the cartItem
=> feat: add functions for local storage management and page redirection

src/main/resources/templates/admin/member.html
=> admin member.html add CSS

src/main/resources/static/admin.css
=> make static table css

src/main/resources/templates/admin/member.html
=> delete css style

src/main/java/com/bit/joe/shoppingmall/view/AdminController.java, src/main/resources/templates/admin/add-inventory.html
- Added a new admin page that allows administrators to add new products to the inventory
- Implemented form with fields for product name, category selection, price, quantity, and image URL
- Added new endpoint in AdminController to handle the page navigation
=> Create Admin add inventory

src/main/resources/templates/admin/member.html
- apply admin.css to member.html
=> apply admin.css to member.html

src/main/resources/static/global.js, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/product-detail.html
- Updating cart items' quantity at the Cart Page
- 화면 상에서 quantity 를 증가/감소 시키는 게 바로 바로 적용 됨
> - 변경 전
> <img width="766" alt="image" src="https://github.com/user-attachments/assets/12b16e95-0d91-4fb3-854c-ee57e4fc2f1a" />
> 
> <img width="800" alt="image" src="https://github.com/user-attachments/assets/433348c0-4b8f-4174-b05f-ab4d4111c10f" />
> 
> - 변경 후
> <img width="779" alt="image" src="https://github.com/user-attachments/assets/10185c6c-b5c6-4885-9ebf-7a6135bf2a95" />
> 
> <img width="813" alt="image" src="https://github.com/user-attachments/assets/40437dcf-e164-4e87-aabd-3f6465a3f1e2" />
> 
>
=> Feature, update quantity in the cart page (25.03.12)

src/main/resources/templates/admin/inventory.html
- apply admin.css to inventory.html
=> apply admin.css to inventory.html

src/main/resources/static/global.js, src/main/resources/templates/product/product-detail.html
- BUG
- After updating quantity at the cart page, then return to product-detail page and add product to cart then it does not applied.
- test add to cart button in **product-detail** page
- test modify quantity in **cart** page
=> Fix bug in product-detail, cart view (25.03.12)

src/main/java/com/bit/joe/shoppingmall/controller/CategoryController.java, src/test/java/com/bit/joe/shoppingmall/controller/CategoryControllerTests.java
=> Category Test Code (25.03.12)

src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/resources/templates/admin/update-inventory.html, src/test/java/com/bit/joe/shoppingmall/controller/ProductControllerTests.java
This PR adds and fixes functionality related to product updates in the admin interface
1. Fixed path variable annotation in ProductController
2. Enhanced the update-inventory.html template with proper product update functionality
3. Reordered variable declarations in ProductControllerTests
=> Create Admin to Update Inventory information

src/main/resources/templates/admin/inventory.html
=> checkbox 중앙정렬

src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java, src/main/resources/templates/product/cart.html, src/test/java/com/bit/joe/shoppingmall/controller/CartItemControllerTests.java
=> Add functions cart delete

src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/java/com/bit/joe/shoppingmall/dto/response/Response.java, src/main/java/com/bit/joe/shoppingmall/repository/ProductRepository.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/ProductServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/ProductService.java
- Pagination for product listings and search results to improve application performance and user experience when dealing with large datasets.
=> Paginations for Product

src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java, src/main/resources/templates/product/cart.html
- 카트 비우기 기능 구현
- New feature
- Click "Clear Cart" btn at the Cart view.
=> Cart Clear Function at view (25.03.13)

src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java
- create cart of new user, when he/she signed up.
=> Cart Creation with successful registration

src/main/resources/templates/product/cart.html, src/main/resources/templates/product/history.html
- Checkout (create order, move from cart page to order page)
- New feature
- Click "Proceed to Checkout" button in the cart page
=> Feature, Order and Cart (25.03.13)

src/main/java/com/bit/joe/shoppingmall/controller/CartItemController.java, src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/java/com/bit/joe/shoppingmall/controller/UserController.java, src/main/java/com/bit/joe/shoppingmall/dto/response/Response.java, src/main/java/com/bit/joe/shoppingmall/repository/ProductRepository.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartItemServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/ProductServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/UserServiceImpl.java, src/main/java/com/bit/joe/shoppingmall/service/ProductService.java, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/history.html, src/test/java/com/bit/joe/shoppingmall/controller/CartItemControllerTests.java
- CartItem Test Code
- Run the test.
=> CartItem Test Code (25.03.13)

src/main/java/com/bit/joe/shoppingmall/view/AdminController.java, src/main/resources/templates/admin/insight.html
Admin insight page
- Developing Admin insight page
=> Admin insight page

src/main/java/com/bit/joe/shoppingmall/controller/CartController.java, src/main/java/com/bit/joe/shoppingmall/service/Impl/CartService.java, src/test/java/com/bit/joe/shoppingmall/controller/CartControllerTests.java, src/test/java/com/bit/joe/shoppingmall/controller/CartItemControllerTests.java
- add test code for CartController, CartItemController
=> Test Code for Cart, Cart-Item (25.03.13)

src/main/java/com/bit/joe/shoppingmall/view/AdminController.java, src/main/resources/templates/admin/customerOrders.html, src/main/resources/templates/admin/insight.html, src/main/resources/templates/admin/member.html, src/main/resources/templates/common/navigation.html, src/main/resources/templates/product/cart.html, src/main/resources/templates/product/history.html, src/main/resources/templates/product/product-detail.html, src/main/resources/templates/user/mainPage.html
Check details for functions and styles
- set main size(avoid footer climbing up) 
- added a footer where it isn't present.
- include pagination script code
- added Order History List page in Admin Dashboard
=> Check details for functions and styles

src/main/resources/templates/admin/member.html
=> Remove Password On User Table

src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/resources/templates/admin/add-inventory.html, src/main/resources/templates/admin/inventory.html
- Print all products in admin page
=> Print All Products

src/main/java/com/bit/joe/shoppingmall/controller/ProductController.java, src/main/resources/templates/product/product-detail.html, src/main/resources/templates/user/mainPage.html
fix pagination and product detail
- add endpoint for href in mainPage
- fixed product detail page to be accessed for not logged-in users.
=> fix product detail page

src/main/resources/templates/admin/inventory.html
=> modify subject location

src/main/resources/templates/admin/member.html
=> modify subject

src/main/java/com/bit/joe/shoppingmall/jwt/JWTUtil.java
=> Handling JWT expiration exception (25.03.17)
